### ISSUE TITLE
Unit test utility functions

### ISSUE THREAD

**Issue by jdayton3** [Microsoft/dpu-utils#5]
I'm more likely to use utility functions if I know they've been unit tested. I'm wondering:

* Would your team welcome a pull request to start unit testing?
* If so, what testing framework would you prefer? (I'm most comfortable with Python's builtin [`unittest`](https://docs.python.org/3/library/unittest.html) framework if there's no preference.)

**Comment by mallamanis** [comment]
Hi Jonathan,

Thanks a lot for looking into our library. Yes, having unit tests would great! We would certainly welcome one or more PRs on this. I am fine with using `unittest`.

If you have time to work on this, I would suggest that you submit relatively short PRs adding a few tests each time. This will be much easier for reviewing the PRs and getting any feedback early.

Looking forward to a PR! :)
