### ISSUE TITLE
pip install dpu-utils error

### ISSUE THREAD

**Issue by s1530129650** [microsoft/dpu-utils#56]
OS：window10
python: 3.5

when I run "pip install dpu-utils"

Collecting dpu-utils
  Using cached dpu_utils-0.1.27-py2.py3-none-any.whl (39 kB)
Requirement already satisfied: tqdm in c:\users\v-ensh\anaconda3\envs\tf1\lib\site-packages (from dpu-utils) (4.50.2)
Requirement already satisfied: docopt in c:\users\v-ensh\anaconda3\envs\tf1\lib\site-packages (from dpu-utils) (0.6.2)
Collecting SetSimilaritySearch
  Using cached SetSimilaritySearch-0.1.7-py2.py3-none-any.whl (14 kB)
Requirement already satisfied: numpy in c:\users\v-ensh\anaconda3\envs\tf1\lib\site-packages (from dpu-utils) (1.18.5)
Collecting azure-storage
  Using cached azure-storage-0.37.0.zip (4.3 kB)

 ERROR: Command errored out with exit status 1:
     command: 'c:\users\v-ensh\anaconda3\envs\tf1\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\v-ensh\\AppData\\Local\\Temp\\pip-install-5cnwyk75\\az
ure-storage\\setup.py'"'"'; __file__='"'"'C:\\Users\\v-ensh\\AppData\\Local\\Temp\\pip-install-5cnwyk75\\azure-storage\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__
);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\v-ensh\AppData\Local\Temp\pip-pip-egg-info-
ejvmcyn5'
         cwd: C:\Users\v-ensh\AppData\Local\Temp\pip-install-5cnwyk75\azure-storage\
    Complete output (19 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\v-ensh\AppData\Local\Temp\pip-install-5cnwyk75\azure-storage\setup.py", line 55, in <module>
        raise RuntimeError(message)
    RuntimeError:
    
    Starting with v0.37.0, the 'azure-storage' meta-package is deprecated and cannot be installed anymore.
    Please install the service specific packages prefixed by `azure` needed for your application.
    
    The complete list of available packages can be found at:
    https://aka.ms/azsdk/python/all
    
    Here's a non-exhaustive list of common packages:
    
    - [azure-storage-blob](https://pypi.org/project/azure-storage-blob) : Blob storage client
    - [azure-storage-file-share](https://pypi.org/project/azure-storage-file-share) : Storage file share client
    - [azure-storage-file-datalake](https://pypi.org/project/azure-storage-file-datalake) : ADLS Gen2 client
    - [azure-storage-queue](https://pypi.org/project/azure-storage-queue): Queue storage client
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output

I run python setup.py egg_info
this is log
[OpenGNN.egg-info.zip](https://github.com/microsoft/dpu-utils/files/5485560/OpenGNN.egg-info.zip)

**Comment by mallamanis** [comment]
Hi @s1530129650 , I am aware of this issue caused by updated downstream dependencies. Although we're currently working to fix this, the package's latest version should still be functional can you try
```
pip install --no-cache-dir dpu-utils
```
You seem to be installing dpu-utils `0.1.27` whereas the current version is at `0.2.19` (see [here](https://pypi.org/project/dpu-utils/#history)).

**Comment by s1530129650** [comment]
Thanks for your help. It works
