### ISSUE TITLE
Sentencepiece dependency

### ISSUE THREAD

**Issue by SpirinEgor** [microsoft/dpu-utils#67]
Hi!

I tried to install `dpu-utils` for python but it crashed due to an incorrect version of `sentencepiece`. I see in your `setup.py` strong equality to `0.1.92` version, but it was removed to some [bugs](https://github.com/google/sentencepiece/issues/505). Is it possible to use a newer version of that package? Currently, I can install only `0.2.20` version of `dpu-utils` :)

**Comment by khairulislam** [comment]
I have the same issue. 
```
WARNING: The candidate selected for download or install is a yanked version: 'sentencepiece' candidate (version 0.1.92 at https://files.pythonhosted.org/packages/18/f3/2f9006ce3bd44dd4a198dfee37eb5f5bdddcf5f5880c35812c646a92cfa3/sentencepiece-0.1.92.tar.gz#sha256=5daf059b31ef82b52698f86891ed8376550d36a5b87a4a3590a94a255346ee08 (from https://pypi.org/simple/sentencepiece/))
Reason for being yanked: Crash bug is reported (confirming)
Building wheels for collected packages: sentencepiece
  Building wheel for sentencepiece (setup.py) ... error

**Comment by mallamanis** [comment]
Pypi now updated
