### ISSUE TITLE
One bug in keywordlist.py

### ISSUE THREAD

**Issue by shangqing-liu** [microsoft/dpu-utils#79]
Hi,

Thanks for this great tool. It seems one bug in the keywordlist.py when reading the keywords for a specific programming language.

https://github.com/microsoft/dpu-utils/blob/1d749cda064dccf04cf4ce3026d3533029d55aa3/python/dpu_utils/codeutils/keywords/keywordlist.py#L42

The I/O operation will be closed when reading the text contexts. Kindly suggest wrapping the reading process with the file-open operation.

Thanks

**Comment by mallamanis** [comment]
Thanks for noticing! This should be now fixed in [`0.6.1`](https://pypi.org/project/dpu-utils/#history)
